/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_logoutAll"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AuthController_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/empresas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["EmpresasController_listar"];
        put?: never;
        post: operations["EmpresasController_crear"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/empresas/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["EmpresasController_obtener"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["EmpresasController_actualizar"];
        trace?: never;
    };
    "/empleados": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["EmpleadosController_listar"];
        put?: never;
        post: operations["EmpleadosController_crear"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/empleados/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["EmpleadosController_obtener"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["EmpleadosController_actualizar"];
        trace?: never;
    };
    "/empleados/{id}/reset-pin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["EmpleadosController_restablecerPin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/kiosco/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Datos de la empresa para mostrar en el kiosco */
        get: operations["KioscoController_info"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/kiosco/{slug}/estado": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Valida código + PIN y devuelve qué marcajes puede hacer el empleado */
        post: operations["KioscoController_estado"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/kiosco/{slug}/marcajes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Registra un marcaje (la hora la define el servidor) */
        post: operations["KioscoController_marcar"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/marcajes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["MarcajesController_listar"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        LoginDto: {
            /** @example admin@codingiq.com */
            email: string;
            password: string;
        };
        /** @enum {string} */
        Rol: "SUPER_ADMIN" | "ADMIN_EMPRESA";
        UsuarioDto: {
            id: string;
            email: string;
            nombre: string;
            rol: components["schemas"]["Rol"];
            empresaId: string | null;
        };
        LoginResponseDto: {
            /** @description JWT de acceso (15 min). Enviar como Bearer. */
            accessToken: string;
            usuario: components["schemas"]["UsuarioDto"];
        };
        RefreshResponseDto: {
            accessToken: string;
        };
        EmpresaDto: {
            id: string;
            nombre: string;
            slug: string;
            rtn: string | null;
            zonaHoraria: string;
            activa: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        PaginationMetaDto: {
            total: number;
            page: number;
            limit: number;
            totalPages: number;
        };
        EmpresasPaginadasDto: {
            data: components["schemas"]["EmpresaDto"][];
            meta: components["schemas"]["PaginationMetaDto"];
        };
        CreateEmpresaDto: {
            /** @example Pizzería El Sol */
            nombre: string;
            /**
             * @description Se usa en la URL del kiosco. Si se omite se genera desde el nombre.
             * @example pizzeria-el-sol
             */
            slug?: string;
            /** @example 08019999123456 */
            rtn?: string;
            /**
             * @default America/Tegucigalpa
             * @example America/Tegucigalpa
             */
            zonaHoraria: string;
        };
        UpdateEmpresaDto: {
            /** @example Pizzería El Sol */
            nombre?: string;
            /**
             * @description Se usa en la URL del kiosco. Si se omite se genera desde el nombre.
             * @example pizzeria-el-sol
             */
            slug?: string;
            /** @example 08019999123456 */
            rtn?: string;
            /**
             * @default America/Tegucigalpa
             * @example America/Tegucigalpa
             */
            zonaHoraria: string;
            activa?: boolean;
        };
        EmpleadoDto: {
            id: string;
            empresaId: string;
            codigo: string;
            nombre: string;
            apellido: string;
            identidad: string | null;
            cargo: string | null;
            activo: boolean;
            /**
             * Format: date-time
             * @description Si tiene valor futuro, el empleado está bloqueado por intentos fallidos
             */
            bloqueadoHasta: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        EmpleadosPaginadosDto: {
            data: components["schemas"]["EmpleadoDto"][];
            meta: components["schemas"]["PaginationMetaDto"];
        };
        CreateEmpleadoDto: {
            /**
             * Format: uuid
             * @description Obligatorio para SUPER_ADMIN. Se ignora (y se valida) para ADMIN_EMPRESA.
             */
            empresaId?: string;
            /**
             * @description Código que el empleado escribe al marcar. Si se omite se genera uno correlativo.
             * @example 0007
             */
            codigo?: string;
            /**
             * @description PIN de 4 a 6 dígitos. Si se omite se genera uno aleatorio.
             * @example 4827
             */
            pin?: string;
            /** @example María */
            nombre: string;
            /** @example López */
            apellido: string;
            /**
             * @description Número de identidad (13 dígitos)
             * @example 0801199012345
             */
            identidad?: string;
            /** @example Cajera */
            cargo?: string;
        };
        EmpleadoCreadoDto: {
            empleado: components["schemas"]["EmpleadoDto"];
            /** @description PIN en texto plano. Solo se devuelve en esta respuesta. */
            pin: string;
        };
        UpdateEmpleadoDto: {
            /**
             * @description Código que el empleado escribe al marcar. Si se omite se genera uno correlativo.
             * @example 0007
             */
            codigo?: string;
            /** @example María */
            nombre?: string;
            /** @example López */
            apellido?: string;
            /**
             * @description Número de identidad (13 dígitos)
             * @example 0801199012345
             */
            identidad?: string;
            /** @example Cajera */
            cargo?: string;
            activo?: boolean;
        };
        ResetPinDto: {
            /**
             * @description Si se omite se genera uno aleatorio.
             * @example 4827
             */
            pin?: string;
        };
        PinRestablecidoDto: {
            /** @description PIN en texto plano. Solo se devuelve en esta respuesta. */
            pin: string;
        };
        KioscoInfoDto: {
            nombre: string;
            slug: string;
        };
        CredencialesKioscoDto: {
            /** @example 0007 */
            codigo: string;
            /** @example 4827 */
            pin: string;
        };
        EmpleadoKioscoDto: {
            codigo: string;
            nombre: string;
            apellido: string;
        };
        /** @enum {string} */
        TipoMarcaje: "ENTRADA" | "INICIO_ALMUERZO" | "FIN_ALMUERZO" | "SALIDA";
        UltimoMarcajeDto: {
            tipo: components["schemas"]["TipoMarcaje"];
            /** Format: date-time */
            marcadoEn: string;
        };
        EstadoKioscoDto: {
            empleado: components["schemas"]["EmpleadoKioscoDto"];
            ultimoMarcaje: components["schemas"]["UltimoMarcajeDto"] | null;
            /** @description Marcajes que el empleado puede registrar ahora (para mostrar solo esos botones) */
            permitidos: components["schemas"]["TipoMarcaje"][];
        };
        MarcarDto: {
            /** @example 0007 */
            codigo: string;
            /** @example 4827 */
            pin: string;
            tipo: components["schemas"]["TipoMarcaje"];
        };
        MarcarRespuestaDto: {
            tipo: components["schemas"]["TipoMarcaje"];
            /**
             * Format: date-time
             * @description Hora del servidor (UTC, ISO 8601)
             */
            marcadoEn: string;
            empleado: components["schemas"]["EmpleadoKioscoDto"];
            permitidos: components["schemas"]["TipoMarcaje"][];
        };
        EmpleadoResumenDto: {
            id: string;
            codigo: string;
            nombre: string;
            apellido: string;
        };
        MarcajeDto: {
            id: string;
            empresaId: string;
            empleadoId: string;
            tipo: components["schemas"]["TipoMarcaje"];
            /**
             * Format: date-time
             * @description Hora del servidor (UTC, ISO 8601)
             */
            marcadoEn: string;
            empleado: components["schemas"]["EmpleadoResumenDto"];
        };
        MarcajesPaginadosDto: {
            data: components["schemas"]["MarcajeDto"][];
            meta: components["schemas"]["PaginationMetaDto"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponseDto"];
                };
            };
        };
    };
    AuthController_refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefreshResponseDto"];
                };
            };
        };
    };
    AuthController_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_logoutAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsuarioDto"];
                };
            };
        };
    };
    EmpresasController_listar: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
                /** @description Busca por nombre o slug */
                search?: string;
                activa?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmpresasPaginadasDto"];
                };
            };
        };
    };
    EmpresasController_crear: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateEmpresaDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmpresaDto"];
                };
            };
        };
    };
    EmpresasController_obtener: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmpresaDto"];
                };
            };
        };
    };
    EmpresasController_actualizar: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateEmpresaDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmpresaDto"];
                };
            };
        };
    };
    EmpleadosController_listar: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
                /** @description SUPER_ADMIN: filtra por empresa */
                empresaId?: string;
                /** @description Busca por nombre, apellido, código o identidad */
                search?: string;
                activo?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmpleadosPaginadosDto"];
                };
            };
        };
    };
    EmpleadosController_crear: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateEmpleadoDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmpleadoCreadoDto"];
                };
            };
        };
    };
    EmpleadosController_obtener: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmpleadoDto"];
                };
            };
        };
    };
    EmpleadosController_actualizar: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateEmpleadoDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmpleadoDto"];
                };
            };
        };
    };
    EmpleadosController_restablecerPin: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetPinDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PinRestablecidoDto"];
                };
            };
        };
    };
    KioscoController_info: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KioscoInfoDto"];
                };
            };
        };
    };
    KioscoController_estado: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CredencialesKioscoDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EstadoKioscoDto"];
                };
            };
        };
    };
    KioscoController_marcar: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MarcarDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MarcarRespuestaDto"];
                };
            };
        };
    };
    MarcajesController_listar: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
                /** @description SUPER_ADMIN: filtra por empresa */
                empresaId?: string;
                empleadoId?: string;
                tipo?: components["schemas"]["TipoMarcaje"];
                /** @description Inicio del rango (ISO 8601, inclusivo) */
                desde?: string;
                /** @description Fin del rango (ISO 8601, exclusivo) */
                hasta?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MarcajesPaginadosDto"];
                };
            };
        };
    };
}
